// A2A protocol types — re-exported from shared/ (source of truth).
// Local consumers can import from here for convenience.
export type {
  Role,
  Part,
  Message,
  SendMessageRequest,
  SendMessageConfiguration,
  SendMessageResponse,
  A2ARelayQueuedMessage,
  A2ARelayPollRequest,
  A2ARelayPollResponse,
  A2ARelayAckRequest,
  A2ARelayAckResponse,
  A2ARelayIdentity,
  A2ARelayAgentIdentity,
  A2ARelayEnvelope,
  A2AInboundApprovalState,
  A2AInboundApprovalRequest,
  A2ARelayDisposition,
  A2ARelaySession,
  Task,
  TaskState,
  TaskStatus,
  Artifact,
  AgentCard,
  AgentSkill,
  AgentCapabilities,
  AgentInterface,
  AgentProvider,
  AgentExtension,
  TaskStatusUpdateEvent,
  TaskArtifactUpdateEvent,
  GetTaskRequest,
  ListTasksRequest,
  ListTasksResponse,
  CancelTaskRequest,
} from '@chamber/shared/a2a-types';
